version: '3.7'

services:
  modsecurity:
    image: owasp/modsecurity-crs:nginx
    volumes:
      - ./proxypass.conf:/etc/nginx/conf.d/proxypass.conf
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
      - ./crs-setup.conf:/etc/modsecurity.d/owasp-crs/crs-setup.conf


    ports:
      - "80:80"
    environment:
      - SERVER_NAME=modsecexample.com
      - PROXY=1
      - METRICS_ALLOW_FROM=172.0.0.0/24
      - MODSEC_AUDIT_ENGINE=On
      - MANUAL_MODE=1


    networks:
        modsecurity_network:
           ipv4_address: 172.20.0.2

  website1:
    image: nginx
    volumes:
      - ./example1.com:/usr/share/nginx/html
      - ./default1.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=example1.com
    ports:
      - "8081:80"
    networks:
        modsecurity_network:
           ipv4_address: 172.20.0.3

  website2:
    image: nginx
    volumes:
      - ./example2.com:/usr/share/nginx/html
      - ./default2.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=example2.com
    ports:
      - "8082:80"
    networks:
        modsecurity_network:
           ipv4_address: 172.20.0.4

  website3:
    image: nginx
    volumes:
      - ./example3.com:/usr/share/nginx/html
      - ./default3.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=example3.com
    ports:
      - "8083:80"
    networks:
        modsecurity_network:
           ipv4_address: 172.20.0.5

networks:
  modsecurity_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
