version: '3'
networks:
  wordpress-network:
    name: wordpress-network

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}


  modsecurity:
    image: owasp/modsecurity-crs:nginx
    volumes:
      - ./proxypass.conf:/etc/nginx/conf.d/proxypass.conf
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
      - ./crs-setup.conf:/etc/modsecurity.d/owasp-crs/crs-setup.conf


    ports:
      - "80:80"
      - "443:443"
    environment:
      - SERVER_NAME=modsecexample.com
      - PROXY=1
      - MODSEC_AUDIT_ENGINE=On
      - MANUAL_MODE=1

  site1.com:
    image: docker.io/bitnami/wordpress-nginx:latest
    volumes:
      - 028haoen_com_wordpress:/bitnami/wordpress
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=site1
      - WORDPRESS_TABLE_PREFIX=grign_
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD_site1.com}
    depends_on:
      - mariadb
    networks:
      - wordpress-network



  site2.com:
    image: docker.io/bitnami/wordpress-nginx:latest
    volumes:
      - 0898teyi_com_wordpress:/bitnami/wordpress
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=site2
      - WORDPRESS_TABLE_PREFIX=kcfsu_
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD_site2.com}
    depends_on:
      - mariadb
    networks:
      - wordpress-network



  site3.com:
    image: docker.io/bitnami/wordpress-nginx:latest
    volumes:
      - 13719030012jzm_com_wordpress:/bitnami/wordpress
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_NAME=site3
      - WORDPRESS_TABLE_PREFIX=twitw_
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD_site3.com}
    depends_on:
      - mariadb
    networks:
      - wordpress-network





  volumes:
  site1:
    driver: local


  site2:
    driver: local


  site3:
    driver: local



  mariadb_data:
    driver: local
