version: '3.7'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:latest
    ports:
      - '8081:8080'
      - '8444:8443'
    volumes:
      - example1:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
 #     - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP1_PREFIX}
      - WORDPRESS_USERNAME=${WP_USER}
      - WORDPRESS_PASSWORD=${EXAMPLE1_PASS}
      - WP_SITEURL=${SITE1_URL}
      


  wordpress2:
    image: docker.io/bitnami/wordpress-nginx:latest
    ports:
      - '8082:8080'
      - '8445:8443'
    volumes:
      - example2:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #    - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP2_PREFIX}
      - WORDPRESS_USERNAME=${WP_USER}
      - WORDPRESS_PASSWORD=${EXAMPLE2_PASS}
      - WP_SITEURL=${SITE2_URL}

  wordpress3:
    image: docker.io/bitnami/wordpress-nginx:latest
    ports:
      - '8083:8080'
      - '8446:8443'
    volumes:
      - example3:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - WORDPRESS_DATABASE_USER=${DB_USER}
      - WORDPRESS_DATABASE_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DATABASE_NAME=${DB_NAME}
      - WORDPRESS_TABLE_PREFIX=${WP3_PREFIX}
      - WORDPRESS_USERNAME=${WP_USER}
      - WORDPRESS_PASSWORD=${EXAMPLE3_PASS}
      - WP_SITEURL=${SITE3_URL}
      

  modsecurity:
    image: owasp/modsecurity-crs:nginx
    volumes:
      - ./proxypass.conf:/etc/nginx/conf.d/proxypass.conf
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
      - ./crs-setup.conf:/etc/modsecurity.d/owasp-crs/crs-setup.conf


    ports:
      - "80:80"
    environment:
      - SERVER_NAME=modsecexample.com
      - PROXY=1
      - METRICS_ALLOW_FROM=172.0.0.0/24
      - MODSEC_AUDIT_ENGINE=On
      - MANUAL_MODE=1


volumes:
  mariadb_data:
    driver: local
  example1:
    driver: local
  example2:
    driver: local
  example3:
    driver: local
